import './globals.css'
import 'bootstrap/dist/css/bootstrap.css'
import Header from '@/components/header'
import Footer from '@/components/footer'
import { Open_Sans } from 'next/font/google'
import Head from 'next/head'
import Script from 'next/script'

export const metadata = {
  title: 'CALMA - Sunset & Surf',
  description: 'Welcome to Calma Sunset and Surf! where monkeys will wake you up every morning and sunsets over the ocean are accompanied by a dschungle concert.Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossOrigin="anonymous" />
      </Head>
      <Script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/js/all.min.js" crossOrigin="anonymous" />
        <Script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossOrigin="anonymous" />
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.min.js" integrity="sha384-heAjqF+bCxXpCWLa6Zhcp4fu20XoNIA98ecBC1YkdXhszjoejr5y9Q77hIrv8R9i" crossOrigin="anonymous" />
      <body>
        <div className="container-fluid p-0" style={{minHeight:"100vh"}}>
        <Header />
        {children}
        <Footer />
        </div>
      </body>
    </html>
  )
}
