import './globals.css'
import 'bootstrap/dist/css/bootstrap.css'
import Header from '@/components/header'
import Footer from '@/components/footer'
import { Open_Sans } from 'next/font/google'

export const metadata = {
  title: 'CALMA - Sunset & Surf',
  description: 'Welcome to Calma Sunset and Surf! where monkeys will wake you up every morning and sunsets over the ocean are accompanied by a dschungle concert.Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="container-fluid p-0" style={{minHeight:"100vh"}}>
        <Header />
        {children}
        <Footer />
        </div>
      </body>
    </html>
  )
}
